# Generated by Django 4.1 on 2022-08-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csv_processing", "0002_alter_fileuploadmodel_parsed_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileuploadmodel",
            old_name="parsed_file",
            new_name="processed_file",
        ),
    ]
